modLoader="javafml"
loaderVersion="[40,)"
license="GNU GPLv3"
issueTrackerURL="https://github.com/auioc/NotEnoughLuck/issues"

[[mods]]
modId="notenoughluck"
version="${file.jarVersion}"
updateJSONURL="https://hi.auioc.org/NotEnoughLuck/update/1.18.2.json"
displayName="NotEnoughLuck"
displayURL="https://hi.auioc.org/NotEnoughLuck/"
logoFile="icon.png"
credits="AUIOC"
authors="WakelssSloth56,Libellule505"
description='''
Not Enough Luck
'''

[[dependencies.notenoughluck]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notenoughluck]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notenoughluck]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.6.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.notenoughluck]]
    modId="hulsealib"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="NONE"
    side="BOTH"
